import { Rarity, Category, LocationData, SubscriptionConfig, PlanTier } from './types';

export const MAX_LEVEL = 12;
export const DEFAULT_LEVEL = 5; 
export const MAX_DAILY_GENERATIONS = 3;

export const RECUR_CONFIG = {
  PUBLISHABLE_KEY: 'pk_test_95b6695679feee448947ab70433b9628b2006e056c71d49fc251e1323a81468f', 
  PREMIUM_PLAN_ID: 'adkwbl9dya0wc6b53parl9yk' 
};

export const SUBSCRIPTION_PLANS: Record<PlanTier, SubscriptionConfig> = {
  free: {
    id: 'free',
    name: 'Free Starter',
    priceDisplay: '$0 / Month',
    allowedRarities: [Rarity.R],
    maxSlots: 1,
    features: ['發行 R 級優惠券', '同時上架 1 張', '基礎曝光']
  },
  partner: {
    id: 'partner',
    name: 'Partner',
    priceDisplay: '$499 / Month',
    allowedRarities: [Rarity.R, Rarity.S, Rarity.SR],
    maxSlots: 3,
    features: ['解鎖 S/SR 級優惠券', '同時上架 3 張', '每日 1 則跑馬燈']
  },
  premium: {
    id: 'premium',
    name: 'Premium',
    priceDisplay: '$1,499 / Month',
    allowedRarities: [Rarity.R, Rarity.S, Rarity.SR, Rarity.SSR, Rarity.SP],
    maxSlots: 999,
    recurPlanId: RECUR_CONFIG.PREMIUM_PLAN_ID,
    features: ['解鎖 SSR/SP 大獎', '無限發行額度', '無限跑馬燈', '地圖金框特效']
  }
};

export const RARITY_COLORS: Record<Rarity, string> = {
  [Rarity.SP]: '#be185d',
  [Rarity.SSR]: '#b45309',
  [Rarity.SR]: '#7e22ce',
  [Rarity.S]: '#1d4ed8',
  [Rarity.R]: '#334155',
};

export const CATEGORY_COLORS: Record<Category, string> = {
  [Category.Food]: '#ea580c',
  [Category.Stay]: '#0891b2',
  [Category.Education]: '#7c3aed',
  [Category.Entertainment]: '#db2777',
  [Category.Scenery]: '#10b981',
  [Category.Shopping]: '#f59e0b',
  [Category.Activity]: '#84cc16',
};

export const SUB_CATEGORY_TAGS = {
  [Category.Food]: [
    "Michelin/Bib Gourmand (米其林/必比登)", "Hidden Gem Cafe (巷弄咖啡)", "Local Breakfast (在地早餐)", 
    "Traditional Dessert (古早味甜點)", "Late Night Supper/Rechao (宵夜/熱炒)", "Street Food/Snack (銅板美食)",
    "Ramen/Soba (拉麵/蕎麥麵)", "Izakaya/Bar (居酒屋/餐酒館)", "Hot Pot (火鍋)", "Steak/Teppanyaki (牛排/鐵板燒)",
    "Vegetarian (素食/蔬食)", "Seafood Restaurant (海鮮餐廳)", "Theme Restaurant (主題餐廳)"
  ],
  [Category.Stay]: [
    "Design Hotel (設計旅店)", "Hot Spring/Ryokan (溫泉飯店/旅館)", "Luxury Camping/Glamping (豪華露營)", 
    "Historic Homestay (老宅民宿)", "Seaview/Mountain View (海景/山景住宿)", "Backpacker Hostel (青年旅館)", 
    "Business Hotel (商務旅館)", "Luxury 5-Star (五星級飯店)"
  ],
  [Category.Scenery]: [
    "IG Photo Spot (網美打卡點)", "Historical Old Street (懷舊老街)", "Secret Viewpoint (私房景點/秘境)", 
    "Night View (百萬夜景)", "Temple/Shrine (寺廟/神社)", "Waterfront/Pier (水岸/碼頭)", 
    "Seasonal Flower/Nature (賞花/自然生態)", "Architectural Landmark (特色建築)", "Urban Park (城市公園)"
  ],
  [Category.Shopping]: [
    "Select Shop/Boutique (風格選物店)", "Local Souvenir (在地伴手禮)", "Vintage/Second-hand (古著/二手)", 
    "Creative Market (文創市集)", "Drugstore/Cosmetics (藥妝)", "Department Store (百貨公司)", 
    "Outlet Mall (暢貨中心)", "Anime/Gacha Shop (動漫/扭蛋店)", "Traditional Market (傳統市場)"
  ],
  [Category.Education]: [
    "Cultural & Creative Park (文創園區)", "Interactive Museum (互動博物館)", "Art Gallery/Exhibition (美術館/展覽)", 
    "Historical Site/Monument (古蹟遺址)", "Public Library (特色圖書館)", "Science Center (科教館)", 
    "Local Workshop (在地工坊)", "Botanical Garden (植物園)"
  ],
  [Category.Entertainment]: [
    "Claw Machine/Arcade (夾娃娃/遊樂場)", "Karaoke/KTV (KTV/卡拉OK)", "Escape Room (密室逃脫)", 
    "Board Game Cafe (桌遊店)", "Live House/Jazz Bar (音樂展演空間)", "Cinema (電影院)", 
    "Bowling/Batting Cage (保齡球/打擊場)", "Theme Park (主題樂園)"
  ],
  [Category.Activity]: [
    "DIY Workshop (手作體驗-陶藝/金工)", "Massage/Spa/Foot Bath (按摩/足湯)", "Cycling/Biking (自行車/單車)", 
    "Hiking Trail (登山步道)", "Water Sports/SUP (水上活動)", "Farm Experience/Fruit Picking (農場/採果)", 
    "Tea Ceremony/Tasting (品茶/茶道)", "Cooking Class (烹飪教室)", "Kimono/Costume Rental (變裝體驗)"
  ]
};

export const TRANSLATIONS = {
  'zh-TW': {
    dailyLimitReached: '今日額度已達上限',
    dailyLimitReachedDesc: '每日最多生成 3 次行程。請明天再來！',
    paymentSuccess: '付款成功！您已升級為 Premium 商家。',
    // UI
    appTitle: '行程扭蛋',
    appSubtitle: 'AI 旅遊扭蛋',
    destination: '目的地',
    selectDestination: '選擇目的地',
    city: '城市',
    selectCity: '選擇城市',
    intensity: '行程數量',
    chill: '休閒',
    standard: '標準',
    hardcore: '充實',
    startGacha: '開始扭蛋',
    generating: '生成中...',
    findingGems: '正在尋找隱藏景點',
    tripLevel: 'Lv.{level} 之旅',
    spotsCount: '{count} 個景點',
    couponUnlocked: '獲得優惠券',
    specialPromo: '特惠活動',
    noCollection: '尚未有收藏',
    startToCollect: '開始扭蛋來收集景點！',
    noCoupons: '尚未有優惠券',
    lucky: '太幸運了！',
    foundCoupon: '你發現了一張隱藏優惠券！',
    collectReward: '領取獎勵',
    // Nav
    navGacha: '扭蛋',
    navCollection: '圖鑑',
    navMyBox: '道具箱',
    navStore: '商家',
    // Merchant
    merchantAccess: '商家登入',
    manageStore: '管理您的商店',
    storeName: '商店名稱',
    enterDashboard: '進入後台',
    activeCoupons: '上架中的優惠券',
    createCampaign: '建立新活動',
    impressions: '曝光次數',
    redeems: '兌換次數',
    login: '登入',
    upgradeTitle: '升級為合作夥伴',
    benefitRarity: '發行更高稀有度 (SR)',
    benefitSlots: '更多上架欄位',
    viewPlans: '查看方案',
    signInGoogle: '使用 Google 登入',
    signInReplit: '使用 Replit 登入',
    or: '或',
    guestLogin: '訪客登入',
    welcomeBack: '歡迎回來',
    loading: '載入中...',
    merchantLogin: '商家登入',
    merchantName: '商家名稱',
    merchantEmail: '商家電子郵件',
    backToHome: '返回首頁',
    catFood: '美食',
    catStay: '住宿',
    catScenery: '景點',
    catShopping: '購物',
    catEntertainment: '娛樂',
    catEducation: '文化',
    catActivity: '活動'
  },
  'en': {
    dailyLimitReached: 'Daily Limit Reached',
    dailyLimitReachedDesc: 'You can generate up to 3 itineraries per day. Come back tomorrow!',
    paymentSuccess: 'Payment Successful! You are now a Premium Merchant.',
    // UI
    appTitle: 'MIBU TRIP',
    appSubtitle: 'AI Travel Gacha',
    destination: 'Destination',
    selectDestination: 'Select Destination',
    city: 'City',
    selectCity: 'Select City',
    intensity: 'Intensity Level',
    chill: 'Chill',
    standard: 'Standard',
    hardcore: 'Hardcore',
    startGacha: 'START GACHA',
    generating: 'Generating...',
    findingGems: 'Finding hidden gems',
    tripLevel: 'Level {level} Trip',
    spotsCount: '{count} Spots',
    couponUnlocked: 'Coupon Unlocked',
    specialPromo: 'Special Promo',
    noCollection: 'No collection yet.',
    startToCollect: 'Start gacha to collect spots!',
    noCoupons: 'No coupons yet.',
    lucky: 'LUCKY!',
    foundCoupon: 'You found a hidden coupon!',
    collectReward: 'Collect Reward',
    // Nav
    navGacha: 'Gacha',
    navCollection: 'Collection',
    navMyBox: 'My Box',
    navStore: 'Store',
    // Merchant
    merchantAccess: 'Merchant Access',
    manageStore: 'Manage your store presence',
    storeName: 'Store Name',
    enterDashboard: 'Enter Dashboard',
    activeCoupons: 'Your Active Coupons',
    createCampaign: 'Create New Campaign',
    impressions: 'Impressions',
    redeems: 'Redeems',
    login: 'Login',
    upgradeTitle: 'Upgrade to Partner',
    benefitRarity: 'Higher Rarity (SR)',
    benefitSlots: 'More Slots',
    viewPlans: 'View Plans',
    signInGoogle: 'Sign in with Google',
    signInReplit: 'Sign in with Replit',
    or: 'or',
    guestLogin: 'Guest Login',
    welcomeBack: 'Welcome Back',
    loading: 'Loading...',
    merchantLogin: 'Merchant Login',
    merchantName: 'Merchant Name',
    merchantEmail: 'Merchant Email',
    backToHome: 'Back to Home',
    catFood: 'Food',
    catStay: 'Stay',
    catScenery: 'Scenery',
    catShopping: 'Shopping',
    catEntertainment: 'Entertainment',
    catEducation: 'Culture',
    catActivity: 'Activity'
  },
  'ja': {
    dailyLimitReached: '本日の上限に達しました',
    dailyLimitReachedDesc: '1日3回まで生成可能です。また明日お越しください！',
    paymentSuccess: '支払いが完了しました！Premiumプランにアップグレードされました。',
    // UI
    appTitle: 'MIBU 旅ガチャ',
    appSubtitle: 'AI トラベルガチャ',
    destination: '目的地',
    selectDestination: '目的地を選択',
    city: '都市',
    selectCity: '都市を選択',
    intensity: '旅行スタイル',
    chill: 'ゆったり',
    standard: '標準',
    hardcore: 'ハード',
    startGacha: 'ガチャを回す',
    generating: '生成中...',
    findingGems: '隠れた名店を探しています',
    tripLevel: 'Lv.{level} の旅',
    spotsCount: '{count} スポット',
    couponUnlocked: 'クーポン獲得',
    specialPromo: '限定プロモ',
    noCollection: 'コレクションはまだありません',
    startToCollect: 'ガチャを回してスポットを集めよう！',
    noCoupons: 'クーポンはまだありません',
    lucky: 'ラッキー！',
    foundCoupon: '隠しクーポンを発見しました！',
    collectReward: '報酬を受け取る',
    // Nav
    navGacha: 'ガチャ',
    navCollection: '図鑑',
    navMyBox: '道具箱',
    navStore: '店舗',
    // Merchant
    merchantAccess: '店舗ログイン',
    manageStore: '店舗情報の管理',
    storeName: '店舗名',
    enterDashboard: 'ダッシュボードへ',
    activeCoupons: '配信中のクーポン',
    createCampaign: '新規キャンペーン作成',
    impressions: '表示回数',
    redeems: '利用回数',
    login: 'ログイン',
    upgradeTitle: 'パートナーにアップグレード',
    benefitRarity: '高レアリティ (SR) 解放',
    benefitSlots: '枠数追加',
    viewPlans: 'プランを見る',
    signInGoogle: 'Googleでログイン',
    signInReplit: 'Replitでログイン',
    or: 'または',
    guestLogin: 'ゲストログイン',
    welcomeBack: 'おかえりなさい',
    loading: '読み込み中...',
    merchantLogin: '店舗ログイン',
    merchantName: '店舗名',
    merchantEmail: 'メールアドレス',
    backToHome: 'ホームに戻る',
    catFood: 'グルメ',
    catStay: '宿泊',
    catScenery: '観光',
    catShopping: 'ショッピング',
    catEntertainment: 'エンタメ',
    catEducation: '文化',
    catActivity: 'アクティビティ'
  },
  'ko': {
    dailyLimitReached: '일일 한도 도달',
    dailyLimitReachedDesc: '하루에 최대 3개의 여행 일정을 생성할 수 있습니다. 내일 다시 와주세요!',
    paymentSuccess: '결제 성공! 이제 프리미엄 판매자입니다.',
    // UI
    appTitle: 'MIBU 트립',
    appSubtitle: 'AI 여행 가챠',
    destination: '목적지',
    selectDestination: '목적지 선택',
    city: '도시',
    selectCity: '도시 선택',
    intensity: '여행 강도',
    chill: '힐링',
    standard: '표준',
    hardcore: '하드코어',
    startGacha: '가챠 시작',
    generating: '생성 중...',
    findingGems: '숨겨진 명소를 찾는 중',
    tripLevel: 'Lv.{level} 여행',
    spotsCount: '{count}개 장소',
    couponUnlocked: '쿠폰 획득',
    specialPromo: '특별 프로모션',
    noCollection: '아직 컬렉션이 없습니다.',
    startToCollect: '가챠를 돌려 장소를 수집하세요!',
    noCoupons: '아직 쿠폰이 없습니다.',
    lucky: '럭키!',
    foundCoupon: '숨겨진 쿠폰을 발견했습니다!',
    collectReward: '보상 받기',
    // Nav
    navGacha: '가챠',
    navCollection: '도감',
    navMyBox: '보관함',
    navStore: '스토어',
    // Merchant
    merchantAccess: '판매자 로그인',
    manageStore: '스토어 관리',
    storeName: '스토어 이름',
    enterDashboard: '대시보드 입장',
    activeCoupons: '진행 중인 쿠폰',
    createCampaign: '새 캠페인 만들기',
    impressions: '노출 수',
    redeems: '사용 수',
    login: '로그인',
    upgradeTitle: '파트너로 업그레이드',
    benefitRarity: '더 높은 희귀도 (SR)',
    benefitSlots: '더 많은 슬롯',
    viewPlans: '요금제 보기',
    signInGoogle: 'Google로 로그인',
    signInReplit: 'Replit으로 로그인',
    or: '또는',
    guestLogin: '게스트 로그인',
    welcomeBack: '환영합니다',
    loading: '로딩 중...',
    merchantLogin: '판매자 로그인',
    merchantName: '상점 이름',
    merchantEmail: '이메일 주소',
    backToHome: '홈으로 돌아가기',
    catFood: '맛집',
    catStay: '숙박',
    catScenery: '관광',
    catShopping: '쇼핑',
    catEntertainment: '엔터테인먼트',
    catEducation: '문화',
    catActivity: '액티비티'
  }
};

export const LOCATION_DATA: LocationData = {
  taiwan: {
    names: { 'zh-TW': '台灣', en: 'Taiwan', ja: '台湾', ko: '대만' },
    cities: {
      keelung: { 'zh-TW': '基隆市', en: 'Keelung City', ja: '基隆市', ko: '지룽시' },
      taipei: { 'zh-TW': '台北市', en: 'Taipei City', ja: '台北市', ko: '타이베이시' },
      new_taipei: { 'zh-TW': '新北市', en: 'New Taipei City', ja: '新北市', ko: '신베이시' },
      taoyuan: { 'zh-TW': '桃園市', en: 'Taoyuan City', ja: '桃園市', ko: '타오위안시' },
      hsinchu_city: { 'zh-TW': '新竹市', en: 'Hsinchu City', ja: '新竹市', ko: '신주와시' },
      hsinchu_county: { 'zh-TW': '新竹縣', en: 'Hsinchu County', ja: '新竹県', ko: '신주현' },
      miaoli: { 'zh-TW': '苗栗縣', en: 'Miaoli County', ja: '苗栗県', ko: '먀오리현' },
      taichung: { 'zh-TW': '台中市', en: 'Taichung City', ja: '台中市', ko: '타이중시' },
      changhua: { 'zh-TW': '彰化縣', en: 'Changhua County', ja: '彰化県', ko: '장화현' },
      nantou: { 'zh-TW': '南投縣', en: 'Nantou County', ja: '南投県', ko: '난터우현' },
      yunlin: { 'zh-TW': '雲林縣', en: 'Yunlin County', ja: '雲林県', ko: '윈린현' },
      chiayi_city: { 'zh-TW': '嘉義市', en: 'Chiayi City', ja: '嘉義市', ko: '자이시' },
      chiayi_county: { 'zh-TW': '嘉義縣', en: 'Chiayi County', ja: '嘉義県', ko: '자이현' },
      tainan: { 'zh-TW': '台南市', en: 'Tainan City', ja: '台南市', ko: '타이난시' },
      kaohsiung: { 'zh-TW': '高雄市', en: 'Kaohsiung City', ja: '高雄市', ko: '가오슝시' },
      pingtung: { 'zh-TW': '屏東縣', en: 'Pingtung County', ja: '屏東県', ko: '핑둥현' },
      yilan: { 'zh-TW': '宜蘭縣', en: 'Yilan County', ja: '宜蘭県', ko: '이란현' },
      hualien: { 'zh-TW': '花蓮縣', en: 'Hualien County', ja: '花蓮県', ko: '화롄현' },
      taitung: { 'zh-TW': '台東縣', en: 'Taitung County', ja: '台東県', ko: '타이둥현' },
      penghu: { 'zh-TW': '澎湖縣', en: 'Penghu County', ja: '澎湖県', ko: '펑후현' },
      kinmen: { 'zh-TW': '金門縣', en: 'Kinmen County', ja: '金門県', ko: '진먼현' },
      lienchiang: { 'zh-TW': '連江縣 (馬祖)', en: 'Lienchiang County', ja: '連江県', ko: '롄장현' },
    },
  },
  japan: {
    names: { 'zh-TW': '日本', en: 'Japan', ja: '日本', ko: '일본' },
    cities: {
      hokkaido: { 'zh-TW': '北海道', en: 'Hokkaido', ja: '北海道', ko: '홋카이도' },
      aomori: { 'zh-TW': '青森縣', en: 'Aomori', ja: '青森県', ko: '아오모리현' },
      iwate: { 'zh-TW': '岩手縣', en: 'Iwate', ja: '岩手県', ko: '이와테현' },
      miyagi: { 'zh-TW': '宮城縣', en: 'Miyagi', ja: '宮城県', ko: '미야기현' },
      akita: { 'zh-TW': '秋田縣', en: 'Akita', ja: '秋田県', ko: '아키타현' },
      yamagata: { 'zh-TW': '山形縣', en: 'Yamagata', ja: '山形県', ko: '야마가타현' },
      fukushima: { 'zh-TW': '福島縣', en: 'Fukushima', ja: '福島県', ko: '후쿠시마현' },
      ibaraki: { 'zh-TW': '茨城縣', en: 'Ibaraki', ja: '茨城県', ko: '이바라키현' },
      tochigi: { 'zh-TW': '櫪木縣', en: 'Tochigi', ja: '栃木県', ko: '도치기현' },
      gunma: { 'zh-TW': '群馬縣', en: 'Gunma', ja: '群馬県', ko: '군마현' },
      saitama: { 'zh-TW': '埼玉縣', en: 'Saitama', ja: '埼玉県', ko: '사이타마현' },
      chiba: { 'zh-TW': '千葉縣', en: 'Chiba', ja: '千葉県', ko: '지바현' },
      tokyo: { 'zh-TW': '東京都', en: 'Tokyo', ja: '東京都', ko: '도쿄도' },
      kanagawa: { 'zh-TW': '神奈川縣', en: 'Kanagawa', ja: '神奈川県', ko: '가나가와현' },
      niigata: { 'zh-TW': '新潟縣', en: 'Niigata', ja: '新潟県', ko: '니가타현' },
      toyama: { 'zh-TW': '富山縣', en: 'Toyama', ja: '富山県', ko: '도야마현' },
      ishikawa: { 'zh-TW': '石川縣', en: 'Ishikawa', ja: '石川県', ko: '이시카와현' },
      fukui: { 'zh-TW': '福井縣', en: 'Fukui', ja: '福井県', ko: '후쿠이현' },
      yamanashi: { 'zh-TW': '山梨縣', en: 'Yamanashi', ja: '山梨県', ko: '야마나시현' },
      nagano: { 'zh-TW': '長野縣', en: 'Nagano', ja: '長野県', ko: '나가노현' },
      gifu: { 'zh-TW': '岐阜縣', en: 'Gifu', ja: '岐阜県', ko: '기후현' },
      shizuoka: { 'zh-TW': '靜岡縣', en: 'Shizuoka', ja: '静岡県', ko: '시즈오카현' },
      aichi: { 'zh-TW': '愛知縣', en: 'Aichi', ja: '愛知県', ko: '아이치현' },
      mie: { 'zh-TW': '三重縣', en: 'Mie', ja: '三重県', ko: '미에현' },
      shiga: { 'zh-TW': '滋賀縣', en: 'Shiga', ja: '滋賀県', ko: '시가현' },
      kyoto: { 'zh-TW': '京都府', en: 'Kyoto', ja: '京都府', ko: '교토부' },
      osaka: { 'zh-TW': '大阪府', en: 'Osaka', ja: '大阪府', ko: '오사카부' },
      hyogo: { 'zh-TW': '兵庫縣', en: 'Hyogo', ja: '兵庫県', ko: '효고현' },
      nara: { 'zh-TW': '奈良縣', en: 'Nara', ja: '奈良県', ko: '나라현' },
      wakayama: { 'zh-TW': '和歌山縣', en: 'Wakayama', ja: '和歌山県', ko: '와카야마현' },
      tottori: { 'zh-TW': '鳥取縣', en: 'Tottori', ja: '鳥取県', ko: '돗토리현' },
      shimane: { 'zh-TW': '島根縣', en: 'Shimane', ja: '島根県', ko: '시마네현' },
      okayama: { 'zh-TW': '岡山縣', en: 'Okayama', ja: '岡山県', ko: '오카야마현' },
      hiroshima: { 'zh-TW': '廣島縣', en: 'Hiroshima', ja: '広島県', ko: '히로시마현' },
      yamaguchi: { 'zh-TW': '山口縣', en: 'Yamaguchi', ja: '山口県', ko: '야마구치현' },
      tokushima: { 'zh-TW': '德島縣', en: 'Tokushima', ja: '徳島県', ko: '도쿠시마현' },
      kagawa: { 'zh-TW': '香川縣', en: 'Kagawa', ja: '香川県', ko: '가가와현' },
      ehime: { 'zh-TW': '愛媛縣', en: 'Ehime', ja: '愛媛県', ko: '에히메현' },
      kochi: { 'zh-TW': '高知縣', en: 'Kochi', ja: '高知県', ko: '고치현' },
      fukuoka: { 'zh-TW': '福岡縣', en: 'Fukuoka', ja: '福岡県', ko: '후쿠오카현' },
      saga: { 'zh-TW': '佐賀縣', en: 'Saga', ja: '佐賀県', ko: '사가현' },
      nagasaki: { 'zh-TW': '長崎縣', en: 'Nagasaki', ja: '長崎県', ko: '나가사키현' },
      kumamoto: { 'zh-TW': '熊本縣', en: 'Kumamoto', ja: '熊本県', ko: '구마모토현' },
      oita: { 'zh-TW': '大分縣', en: 'Oita', ja: '大分県', ko: '오이타현' },
      miyazaki: { 'zh-TW': '宮崎縣', en: 'Miyazaki', ja: '宮崎県', ko: '미야자키현' },
      kagoshima: { 'zh-TW': '鹿兒島縣', en: 'Kagoshima', ja: '鹿児島県', ko: '가고시마현' },
      okinawa: { 'zh-TW': '沖繩縣', en: 'Okinawa', ja: '沖縄県', ko: '오키나와현' },
    },
  },
  hong_kong: {
      names: {'zh-TW': '香港', en: 'Hong Kong', ja: '香港', ko: '홍콩'},
      cities: {
          hong_kong: {'zh-TW': '香港', en: 'Hong Kong', ja: '香港', ko: '홍콩'}
      }
  }
};

export const DISTRICT_DATA: Record<string, Record<string, string[]>> = {
  taiwan: {
    taipei: ['中正區', '大同區', '中山區', '松山區', '大安區', '萬華區', '信義區', '士林區', '北投區', '內湖區', '南港區', '文山區'],
    new_taipei: ['板橋區', '三重區', '中和區', '永和區', '新莊區', '新店區', '土城區', '蘆洲區', '汐止區', '樹林區', '鶯歌區', '三峽區', '淡水區', '瑞芳區', '五股區', '泰山區', '林口區', '深坑區', '石碇區', '坪林區', '三芝區', '石門區', '八里區', '平溪區', '雙溪區', '貢寮區', '金山區', '萬里區', '烏來區'],
    taoyuan: ['桃園區', '中壢區', '平鎮區', '八德區', '楊梅區', '蘆竹區', '大溪區', '龍潭區', '龜山區', '大園區', '觀音區', '新屋區', '復興區'],
    taichung: ['中區', '東區', '南區', '西區', '北區', '北屯區', '西屯區', '南屯區', '太平區', '大里區', '霧峰區', '烏日區', '豐原區', '后里區', '石岡區', '東勢區', '和平區', '新社區', '潭子區', '大雅區', '神岡區', '大肚區', '沙鹿區', '龍井區', '梧棲區', '清水區', '大甲區', '外埔區', '大安區'],
    tainan: ['中西區', '東區', '南區', '北區', '安平區', '安南區', '永康區', '歸仁區', '新化區', '左鎮區', '玉井區', '楠西區', '南化區', '仁德區', '關廟區', '龍崎區', '官田區', '麻豆區', '佳里區', '西港區', '七股區', '將軍區', '學甲區', '北門區', '新營區', '後壁區', '白河區', '東山區', '六甲區', '下營區', '柳營區', '鹽水區', '善化區', '大內區', '山上區', '新市區', '安定區'],
    kaohsiung: ['楠梓區', '左營區', '鼓山區', '三民區', '鹽埕區', '前金區', '新興區', '苓雅區', '前鎮區', '旗津區', '小港區', '鳳山區', '大寮區', '林園區', '大樹區', '大社區', '仁武區', '鳥松區', '岡山區', '橋頭區', '燕巢區', '田寮區', '阿蓮區', '路竹區', '湖內區', '茄萣區', '永安區', '彌陀區', '梓官區', '旗山區', '美濃區', '六龜區', '甲仙區', '杉林區', '內門區', '茂林區', '桃源區', '那瑪夏區'],
    keelung: ['仁愛區', '信義區', '中正區', '中山區', '安樂區', '暖暖區', '七堵區'],
    hsinchu_city: ['東區', '北區', '香山區'],
    chiayi_city: ['東區', '西區'],
  },
  japan: {
    tokyo: ['千代田區', '中央區', '港區', '新宿區', '文京區', '台東區', '墨田區', '江東區', '品川區', '目黑區', '大田區', '世田谷區', '渋谷區', '中野區', '杉並區', '豐島區', '北區', '荒川區', '板橋區', '練馬區', '足立區', '葛飾區', '江戸川區'],
    osaka: ['北區', '都島區', '福島區', '此花區', '中央區', '西區', '港區', '大正區', '天王寺區', '浪速區', '西淀川區', '淀川區', '東淀川區', '東成區', '生野區', '旭區', '城東區', '鶴見區', '阿倍野區', '住之江區', '住吉區', '東住吉區', '平野區', '西成區'],
    kyoto: ['北區', '上京區', '左京區', '中京區', '東山區', '下京區', '南區', '右京區', '伏見區', '山科區', '西京區'],
    fukuoka: ['東區', '博多區', '中央區', '南區', '城南區', '早良區', '西區'],
    sapporo: ['中央區', '北區', '東區', '白石區', '厚別區', '豐平區', '清田區', '南區', '西區', '手稻區'],
  },
  hong_kong: {
    hong_kong: ['中西區', '灣仔區', '東區', '南區', '油尖旺區', '深水埗區', '九龍城區', '黃大仙區', '觀塘區', '葵青區', '荃灣區', '屯門區', '元朗區', '北區', '大埔區', '沙田區', '西貢區', '離島區'],
  }
};
